FROM registry.twilio.com/library/java/build-maven-jdk-17-corretto

# Set working directory
WORKDIR /app

COPY . .

RUN mvn dependency:go-offline

# You can customize the entrypoint as needed. If you need to run additional post-scripts, 
# consider extracting this into a separate .sh file and executing it.
ENTRYPOINT ["mvn", "test",  "-o"]