#!/bin/bash
set -e

green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

printf "${yellow}Running eslint and unit tests...${no_color}\n"
make lint
if ret=$(script -q /dev/null yarn test:unit 2>&1); then
    printf "${green}passed${no_color}\n"
else
    printf "$ret\n"
    exit 1
fi
