require('./spec/Activity');
require('./spec/Channel');
require('./spec/ReservationAccept');
require('./spec/ReservationReject');
require('./spec/Supervisor');
require('./spec/WorkerCommon');
require('./spec/WorkerMultiTask');
require('./spec/WorkerNonMultiTask');
require('./spec/TaskEvents');
